import { clsx, type ClassValue } from 'clsx';
import { twMerge } from 'tailwind-merge';

export function cn(...inputs: ClassValue[]) {
  return twMerge(clsx(inputs));
}

export const LANGUAGES = {
  en: {
    dashboard: 'Overview',
    dailyEntry: 'Staffing',
    import: 'Update Data',
    insights: 'Summary',
    cashier: 'Cashier',
    totalSales: 'Total Sales',
    receipts: 'Receipts',
    weather: 'Weather',
    save: 'Save Record',
    creditCard: 'Credit Card',
    debitCard: 'Debit Card',
    otc: 'OTC',
    coupons: 'Coupons',
    pettyCash: 'Petty Cash',
    checks: 'Checks',
    cashCounting: 'Cash Counting',
    bills: 'Bills',
    ones: '$1',
    fives: '$5',
    tens: '$10',
    twenties: '$20',
    fifties: '$50',
    hundreds: '$100',
    coins: 'Coins',
    totalCash: 'Total Cash',
    suggestedPromos: 'Suggested Promotions',
    generating: 'Analyzing data...',
    history: 'History',
    analysis: 'Staffing',
    comparison: 'YoY Analysis',
    log: 'Products',
    marketRevenue: 'Revenue',
    transactions: 'Transactions',
    unitsSold: 'Items Sold',
    avgBasketValue: 'Avg Basket',
    deptPerformance: 'Category Performance',
    dailyTrend: 'Revenue Trend',
    intradayTrend: 'Hourly Distribution',
    trendingProducts: 'Top Products',
    inventoryAlert: 'Performance Alert: Slow Movers',
    totalSold: 'Volume',
  },
  zh: {
    dashboard: '总览',
    dailyEntry: '人员排班',
    import: '更新数据',
    insights: '摘要',
    cashier: '收银员',
    totalSales: '总销售额',
    receipts: '收据',
    weather: '天气',
    save: '保存记录',
    creditCard: '信用卡',
    debitCard: '借记卡',
    otc: '场外交易',
    coupons: '优惠券',
    pettyCash: '零用现金',
    checks: '支票',
    cashCounting: '现金结算',
    bills: '纸幣',
    ones: '$1',
    fives: '$5',
    tens: '$10',
    twenties: '$20',
    fifties: '$50',
    hundreds: '$100',
    coins: '硬币',
    totalCash: '现金总额',
    suggestedPromos: '建议促销',
    generating: '正在分析数据...',
    history: '历史记录',
    analysis: '人员排班',
    comparison: '年度对比',
    log: '产品与业绩',
    marketRevenue: '收入',
    transactions: '交易量',
    unitsSold: '销售数量',
    avgBasketValue: '平均客单单',
    deptPerformance: '部门业绩',
    dailyTrend: '收入趋势',
    intradayTrend: '按小时分布',
    trendingProducts: '热门商品',
    inventoryAlert: '库存预警：滞销商品',
    totalSold: '销量',
  }
};

export const CATEGORY_MAP: Record<string, string> = {
  '1': 'Hot Food',
  '2': 'Grocery',
  '3': 'Nonfood',
  '4': 'Grocery TX',
  '5': 'Herbal',
  '6': 'Deli',
  '8': 'Cake',
  '9': 'Tea',
  '12': 'BBQ',
  '15': "Abalone/Bird's Nest",
  '16': 'Produce',
  '17': 'Fresh Grocery',
  '18': 'Misc',
  '19': 'Speciality',
  '20': 'Ginseng',
  '21': 'Noodle'
};
